name: Process New MD Files

on:
  push:
    paths:
      - '**/*.md'

jobs:
  process_md:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [-e requirements.txt]; then pip install -r requirements.txt; fi

    - name: Log versions
      run: |
        deno --version
        python --version

    - name: Run Python script
      run: python db/topic_to_db_auto.py
