name: Process New MD Files

on: [push]

jobs:
  process-md:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install system dependencies
      run: |
        apt-get update
        apt-get install -y libsqlite3-dev

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Print working directory and list contents
      run: |
        pwd
        ls -la

    - name: Ensure database file is writable
      run: chmod +w path/to/database/file

    - name: Run topic_to_db_auto.py
      run: python topic_to_db_auto.py